### ISSUE TITLE
Assets folder is not organized

### ISSUE THREAD

**Issue by asror1** [asror1/DesertRush#9]
Hey guys, the contents of the *Assets* folder is a bit too stacked up
It would be perfect if we can organize it because it will 
- Improve efficiency: When files are organized in a logical and consistent manner, it becomes easier and quicker to find the specific file we need. This can save a lot of time and effort in the long run.  
-  Provide scalability: Properly organized files can make it easier to scale the project as it grows. We can add new features or functionality without worrying about how it will affect the rest of the codebase.

**Comment by boatbomber** [comment]
I believe the assets folder is sufficiently organized at this point.
